#     _____  _                       _____                                    _
#    |  __ \| |                     |  __ \                                  | |
#    | |__) | | __ _ _   _  ___ _ __| |__) |_ _ ___ _____      _____  _ __ __| |___
#    |  ___/| |/ _` | | | |/ _ \ '__|  ___/ _` / __/ __\ \ /\ / / _ \| '__/ _` / __|
#    | |    | | (_| | |_| |  __/ |  | |  | (_| \__ \__ \\ V  V / (_) | | | (_| \__ \
#    |_|    |_|\__,_|\__, |\___|_|  |_|   \__,_|___/___/ \_/\_/ \___/|_|  \__,_|___/
#                     __/ |
#                    |___/
#                                Version ${project.version}

# -----------------------------------------
#                 Theme
# -----------------------------------------

# Theme modifies the colors for all text
# used by the plugin that cannot be modified
# under Messages.

# Default: "<gold>"
color1: "<gold>"

# Default: "<yellow>"
color2: "<yellow>"

# Default: "<dark_gray>"
color3: "<dark_gray>"

# -----------------------------------------
#               Settings
# -----------------------------------------

# This allows players to decide if they want to use a password.
Optional: true

# This modifies the minimum and maximum character length of a password.
MinimumPasswordLength: 1
MaximumPasswordLength: 256

# Require the password to be confirmed before being saved.
RequireConfirmation: true

# The maximum number of attempts to get the password right the player can have.
# Use -1 for infinite attempts.
MaxAttempts: 1

# When the player reaches the max attempts, these commands are run.
# Placeholders:
#  - %player% - The player's username.
FailCommands:
  - kick %player% Incorrect Password!

# Block chat when not logged in.
BlockChat: true

# Block commands when not logged in.
BlockCommands: true

# Block interactions with items and blocks while not logged in.
BlockInteract: true

# Block item drop when not logged in.
BlockItemDrop: true

# Block movement when not logged in.
BlockMovement: true

# -----------------------------------------
#               Messages
# -----------------------------------------

# Login
Login: "<color1><bold>Login</bold> <color3>» <gray>You must log in to continue! <color2>/login [password]<gray>."
Register: "<color1><bold>Register</bold> <color3>» <gray>You must register to continue! <color2>/register [password]<gray>."
LogInSuccessful: "<color1><bold>Login</bold> <color3>» <gray>You have logged in successfully."
LoginUsage: "<color1><bold>Login</bold> <color3>» <gray>/login [password]"
ConfirmRegister: "<color1><bold>Register</bold> <color3>» <gray>Confirm your password with <color2>/register confirm [password]<gray>."
RegisterConfirmUsage: "<red><bold>Usage</bold> <color3>» <red>/register confirm [password]."

# Password
PasswordEnabled: "<color1><bold>Password</bold> <color3>» <gray>You have <green>enabled <gray>password protection."
PasswordDisabled: "<color1><bold>Password</bold> <color3>» <gray>You have <red>disabled <gray>password protection."
PasswordNotEnabled: "<color1><bold>Password</bold> <color3>» <gray>Enable your password with /password enable."
PasswordSet: "<color1><bold>Password</bold> <color3>» <gray>Your password has been set to <color2>%password%<gray>."
SetPasswordSuccessful: "<color1><bold>Password</bold> <color3>» <gray>You have successfully set your password."
RegisterUsage: "<red><bold>Usage</bold> <color3>» <red>/register [password]."
PasswordIncorrect: "<red><bold>Error</bold> <color3>» <red>Password Is Incorrect. Try again."
PasswordNotSet: "<red><bold>Error</bold> <color3>» <red>You do not have a password set. Set one with /password set [password]."
PasswordSetUsage: "<red><bold>Usage</bold> <color3>» <red>/password set [password]"
ConfirmPassword: "<color1><bold>Password</bold> <color3>» <gray>Confirm your password with <color2>/password confirm [password]<gray>."
PasswordConfirmUsage: "<red><bold>Usage</bold> <color3>» <gray>/password confirm [password]"

# Errors
AlreadyLoggedIn: "<red><bold>Error</bold> <color3>» <red>You are already logged in!"
AlreadyRegistered: "<red><bold>Error</bold> <color3>» <red>You are already registered!"
NoPermission: "<red><bold>Error</bold> <color3>» <red>You do not have permission to do that."
OutOfBounds: "<red><bold>Error</bold> <color3>» <red>Password must be between <white>%minimum% <red>and <white>%maximum% <red>characters long."
MustBeLoggedIn: "<red><bold>Error</bold> <color3>» <red>You must be logged in to do that."
OptionalPasswordsDisabled: "<red><bold>Error</bold> <color3>» <red>Optional Passwords are disabled."
NotAPlayer: "<red><bold>Error</bold> <color3>» <red>Only players can use that command."
PlayerDoesNotExist: "<red><bold>Error</bold> <color3>» <red>That player does not exist!"

# Other
ConfigReloaded: "<color1><bold>PlayerPasswords</bold> <color3>» <green>Configuration has been reloaded!"
PasswordReset: "<color1><bold>PlayerPasswords</bold> <color3>» <green>Password has been reset successfully!"
PasswordResetUsage: "<red><bold>Usage</bold> <color3>» <red>/password reset [player]"