########  ##          ###    ##    ## ######## ########
##     ## ##         ## ##    ##  ##  ##       ##     ##
##     ## ##        ##   ##    ####   ##       ##     ##
########  ##       ##     ##    ##    ######   ########
##        ##       #########    ##    ##       ##   ##
##        ##       ##     ##    ##    ##       ##    ##
##        ######## ##     ##    ##    ######## ##     ##
########     ###     ######   ######  ##      ##  #######  ########  ########   ######
##     ##   ## ##   ##    ## ##    ## ##  ##  ## ##     ## ##     ## ##     ## ##    ##
##     ##  ##   ##  ##       ##       ##  ##  ## ##     ## ##     ## ##     ## ##
########  ##     ##  ######   ######  ##  ##  ## ##     ## ########  ##     ##  ######
##        #########       ##       ## ##  ##  ## ##     ## ##   ##   ##     ##       ##
##        ##     ## ##    ## ##    ## ##  ##  ## ##     ## ##    ##  ##     ## ##    ##
##        ##     ##  ######   ######   ###  ###   #######  ##     ## ########   ######
name: PlayerPasswords
version: 2.0
main: org.firewolf8385.playerpasswords.PlayerPasswords
database: false
load: POSTWORLD
author: firewolf8385

#####
#     #  ####  #    # #    #   ##   #    # #####   ####
#       #    # ##  ## ##  ##  #  #  ##   # #    # #
#       #    # # ## # # ## # #    # # #  # #    #  ####
#       #    # #    # #    # ###### #  # # #    #      #
#     # #    # #    # #    # #    # #   ## #    # #    #
#####   ####  #    # #    # #    # #    # #####   ####

commands:
  login:
    usage: /<command>
    description: Allows the player to login.
  register:
    usage: /<command>
    description: Allows the player to set their password.
  playerpasswords:
    usage: /<command>
    description: Main plugin command.
    aliases: [playerpassword, pp]
  password:
    usage: /<command>
    description: Player password settings

######
#     # ###### #####  #    # #  ####   ####  #  ####  #    #  ####
#     # #      #    # ##  ## # #      #      # #    # ##   # #
######  #####  #    # # ## # #  ####   ####  # #    # # #  #  ####
#       #      #####  #    # #      #      # # #    # #  # #      #
#       #      #   #  #    # # #    # #    # # #    # #   ## #    #
#       ###### #    # #    # #  ####   ####  #  ####  #    #  ####

permissions:
  playerpasswords.use:
    default: true
    children:
      playerpasswords.enable: true
      playerpasswords.disable: true
      playerpasswords.set: true
  playerpasswords.bypass:
    default: false
  playerpasswords.required:
    default: false